#!/usr/bin/env ruby

require './pagerduty_incidents'
=begin
require "optparse"

options = {}
optparse = OptionParser.new do |opts|
  opts.banner = <<-EOS
  These options are for ...

EOS
  opts.on("--start=START","--from="START","--since=START") {|s| options[:start] = s}
  opts.on("--end=START","--to="START","--until=START") {|e| options[:end] = e}
  opts.on("--month=MONTH", "-m=MONTH") {|m| options[:month] = m}
  opts.on("--year=YEAR", "-y=YEAR") {|y| options[:year] = y}
end
optparse.parse!
=end

responses = PagerdutyIncidents.new()
puts "incidents retrieved.\nexporting data\n"
responses.get_data()
puts "export complete"

